ddvug_willibald_samen:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('DBT_USER') }}"
      ######## These environment variables dbt_user and dbt_password 
      ######## are read from the variabls in Airflow which we will set later
      password: "{{ env_var('DBT_PASSWORD') }}"

      role: ACCOUNTADMIN
      database: "{{ env_var('DBT_DATABASE') }}"
      warehouse: compute_wh
      schema: PUBLIC
      threads: 4