#!/bin/sh
export DWH_DATABASE=
export DWH_SOURCE_DATABASE=
export DWH_PASSWORD=
export DWH_USER=
export DWH_SNOWFLAKE_ACCOUNT=
echo $DWH_DATABASE
echo $DWH_SOURCE_DATABASE
echo $DWH_PASSWORD
echo $DWH_USER
echo $DWH_SNOWFLAKE_ACCOUNT