#!/bin/sh
export DBT_DATABASE=
export DBT_SOURCE_DATABASE=
export DBT_PASSWORD=
export DBT_USER=
export DBT_SNOWFLAKE_ACCOUNT=
echo $DBT_DATABASE
echo $DBT_SOURCE_DATABASE
echo $DBT_PASSWORD
echo $DBT_USER
echo $DBT_SNOWFLAKE_ACCOUNT