CREATE DATABASE dws;
USE DATABASE dws
create or replace schema DWH_01_EXT;

CREATE or REPLACE FILE FORMAT "DWH_01_EXT".FF_SEMICOLON 
COMPRESSION = 'AUTO' FIELD_DELIMITER = ';' RECORD_DELIMITER = '\n' 
SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' TRIM_SPACE = FALSE 
ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE ESCAPE = 'NONE' 
ESCAPE_UNENCLOSED_FIELD = '\134' DATE_FORMAT = 'AUTO' TIMESTAMP_FORMAT = 'AUTO' NULL_IF = ('\\N');


CREATE OR REPLACE STORAGE INTEGRATION DDVUG_WILLIBALD_SAMEN_S3_STORAGE_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  STORAGE_AWS_ROLE_ARN = '<from AWS>'
  ENABLED = TRUE
  STORAGE_ALLOWED_LOCATIONS = ('<S3 Bucket>');

--get STORAGE_AWS_EXTERNAL_ID and STORAGE_AWS_IAM_USER_ARN
DESC INTEGRATION DDVUG_WILLIBALD_SAMEN_S3_STORAGE_INTEGRATION;
  --> AWS -> IAM -> roles -> "role" -> trusted relationship

CREATE or REPlACE STAGE DDVUG_WILLIBALD_SAMEN_S3_STAGE
  STORAGE_INTEGRATION = DDVUG_WILLIBALD_SAMEN_S3_STORAGE_INTEGRATION
  URL = '<S3 Bucket>'
  FILE_FORMAT = "DWH_01_EXT".FF_SEMICOLON;

    ----/misc
--ldts--webshop
    ----\roadshow